name: "generate-snake-game-from-github-contribution-grid-extended"
description: "Generates a snake game from a github user contributions grid. Output the animation as gif or svg"
author: "Arthurlobopro"

runs:
  using: docker
  image: docker://arthurlobo/snk@sha256:36274597d210abbce6cdc1e9a3b507343472747a96003f733f83146028ea251d

inputs:
  github_user_name:
    description: "github user name"
    required: true
  github_token:
    description: "github token used to fetch the contribution calendar. Default to the action token if empty."
    required: false
    default: ${{ github.token }}
  outputs:
    required: false
    description: |
      list of files to generate.
      one file per line. Each output can be customized with options as query string.

       supported query string options:

      - palette:      A preset of color, one of [github, github-dark, github-light]
      - color_snake:  Color of the snake
      - color_dots:   Coma separated list of dots color. 
                      The first one is 0 contribution, then it goes from the low contribution to the highest.
                      Exactly 5 colors are expected.
      - hide_stack: On svg builds, you can hide the progressbar by this option
      example:
        outputs: |
          dark.svg?palette=github-dark&color_snake=blue&hide_stack=true
          light.svg?color_snake=#7845ab
          ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
